### PR TITLE
Update whitelist_sv.js

### PR DESCRIPTION
**Pull request by DeadClap**
On line 9 changed the APIType for the config returning nil when checked later for toLowerCase function

Added missing exports on and below line 100

Added Missing DropPlayer call in playerConnecting event for failed whitelist.

### CODE REVIEW

**Comment by DeadClap** [comment]
The exports are missing in the file, for things like updateBackup, which is called multiples time in existing code but throwing an UnhandledRejection and Unknown Export updateBackup, infoLog, etc

**Comment by DeadClap** [comment]
`(node:10840) UnhandledPromiseRejectionWarning: Error: No such export updateBackup in resource sonorancms
at Object.get (citizen:/scripting/v8/main.js:549:15)
at initialize (@sonorancms/server/modules/whitelist/whitelist_sv.js:107:21)
at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
at onTick (citizen:/scripting/v8/timer.js:227:28)
at citizen:/scripting/v8/timer.js:270:13
at Number.__cfx_wrap_217 (citizen:/scripting/v8/main.js:23:12)
at citizen:/scripting/v8/main.js:29:16
at citizen:/scripting/v8/timer.js:269:16
(Use `FXServer --trace-warnings ...` to show where the warning was created)
(node:10840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

**Comment by DeadClap** [comment]
Will be addressed in #36
Can be closed.

**Comment by Fireant456** [comment]
Thanks for your contributions @DeadClap, it saved us a bit of time needing to diagnose the issue you were encountering. Feel free to keep suggestions and PRs coming. You can chat with other developers and our dev team in #community-development in our discord server https://discord.sonoran.software

**Pull request closed without merging**
